import { Registry } from "@/registry/schema"

const ui: Registry = [
  {
    name: "breadcrumbs",
    type: "components:ui",
    files: ["ui/breadcrumbs.tsx"],
  },
  {
    name: "button-variants",
    type: "components:ui",
    files: ["ui/button-variants.ts"],
  },
  {
    name: "button",
    type: "components:ui",
    registryDependencies: ["ui/button.tsx"],
    files: ["ui/button.tsx"],
  },
  {
    name: "calendar",
    type: "components:ui",
    dependencies: ["react-day-picker", "date-fns"],
    registryDependencies: ["button"],
    files: ["ui/calendar.tsx"],
  },
  {
    name: "checkbox",
    type: "components:ui",
    dependencies: ["@radix-ui/react-checkbox"],
    files: ["ui/checkbox.tsx"],
  },
  {
    name: "combobox",
    type: "components:ui",
    files: ["ui/combobox.tsx"],
  },
  {
    name: "date-picker",
    type: "components:ui",
    dependencies: ["@internationalized/date", "date-fns"],
    registryDependencies: ["calendar", "button", "popover"],
    files: ["ui/date-picker.tsx"],
  },
  {
    name: "dialog",
    type: "components:ui",
    dependencies: ["@radix-ui/react-dialog"],
    files: ["ui/dialog.tsx"],
  },
  {
    name: "dropzone",
    type: "components:ui",
    files: ["ui/dropzone.tsx"],
  },
  {
    name: "input",
    type: "components:ui",
    files: ["ui/input.tsx"],
  },
  {
    name: "label",
    type: "components:ui",
    dependencies: ["@radix-ui/react-label"],
    files: ["ui/label.tsx"],
  },
  {
    name: "link",
    type: "components:ui",
    files: ["ui/link.tsx"],
  },
  {
    name: "menu",
    type: "components:ui",
    files: ["ui/menu.tsx"],
  },
  {
    name: "meter",
    type: "components:ui",
    files: ["ui/meter.tsx"],
  },
  {
    name: "popover",
    type: "components:ui",
    files: ["ui/popover.tsx"],
  },
  {
    name: "progress",
    type: "components:ui",
    files: ["ui/progress.tsx"],
  },
  {
    name: "radio-group",
    type: "components:ui",
    files: ["ui/radio-group.tsx"],
  },
  {
    name: "select",
    type: "components:ui",
    files: ["ui/select.tsx"],
  },
  {
    name: "separator",
    type: "components:ui",
    files: ["ui/separator.tsx"],
  },
  {
    name: "slider",
    type: "components:ui",
    files: ["ui/slider.tsx"],
  },
  {
    name: "switch",
    type: "components:ui",
    files: ["ui/switch.tsx"],
  },
  {
    name: "textarea",
    type: "components:ui",
    files: ["ui/textarea.tsx"],
  },
  {
    name: "toggle",
    type: "components:ui",
    dependencies: ["@radix-ui/react-toggle"],
    files: ["ui/toggle.tsx"],
  },
  {
    name: "tooltip",
    type: "components:ui",
    dependencies: ["@radix-ui/react-tooltip"],
    files: ["ui/tooltip.tsx"],
  },
]
const example: Registry = [
  {
    name: "breadcrumbs-demo",
    type: "components:example",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs-demo.tsx"],
  },
  {
    name: "breadcrumbs-items",
    type: "components:example",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs-items.tsx"],
  },
  {
    name: "button-demo",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-demo.tsx"],
  },
  {
    name: "button-destructive",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-destructive.tsx"],
  },
  {
    name: "button-ghost",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-ghost.tsx"],
  },
  {
    name: "button-secondary",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-secondary.tsx"],
  },
  {
    name: "button-outline",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-outline.tsx"],
  },
  {
    name: "button-press",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-press.tsx"],
  },

  {
    name: "button-link",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-link.tsx"],
  },
  {
    name: "button-with-icon",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-with-icon.tsx"],
  },
  {
    name: "button-loading",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-loading.tsx"],
  },
  {
    name: "button-icon",
    type: "components:example",
    registryDependencies: ["button"],
    files: ["example/button-icon.tsx"],
  },
  {
    name: "calendar-demo",
    type: "components:example",
    registryDependencies: ["calendar"],
    files: ["example/calendar-demo.tsx"],
  },
  {
    name: "checkbox-demo",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-demo.tsx"],
  },
  {
    name: "checkbox-group-demo",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-group-demo.tsx"],
  },
  {
    name: "checkbox-disabled",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-disabled.tsx"],
  },
  {
    name: "checkbox-readonly",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-readonly.tsx"],
  },
  {
    name: "checkbox-indeterminate",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-indeterminate.tsx"],
  },
  {
    name: "checkbox-with-text",
    type: "components:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-with-text.tsx"],
  },
  {
    name: "combobox-demo",
    type: "components:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-demo.tsx"],
  },
  {
    name: "combobox-basic",
    type: "components:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-basic.tsx"],
  },
  {
    name: "combobox-dynamic",
    type: "components:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-dynamic.tsx"],
  },
  {
    name: "combobox-link",
    type: "components:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-link.tsx"],
  },
  {
    name: "combobox-section",
    type: "components:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-section.tsx"],
  },
  {
    name: "date-picker-demo",
    type: "components:example",
    registryDependencies: ["button", "calendar", "popover"],
    files: ["example/date-picker-demo.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "date-picker-with-presets",
    type: "components:example",
    registryDependencies: ["button", "calendar", "popover", "select"],
    files: ["example/date-picker-with-presets.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "dialog-demo",
    type: "components:example",
    registryDependencies: ["dialog"],
    files: ["example/dialog-demo.tsx"],
  },
  {
    name: "dialog-alert-demo",
    type: "components:example",
    registryDependencies: ["dialog"],
    files: ["example/dialog-alert-demo.tsx"],
  },
  {
    name: "dialog-close-button",
    type: "components:example",
    registryDependencies: ["dialog", "button"],
    files: ["example/dialog-close-button.tsx"],
  },
  {
    name: "dropdown-menu-demo",
    type: "components:example",
    registryDependencies: ["menu"],
    files: ["example/dropdown-menu-demo.tsx"],
  },
  {
    name: "dropdown-menu-link",
    type: "components:example",
    registryDependencies: ["menu"],
    files: ["example/dropdown-menu-link.tsx"],
  },
  {
    name: "dropdown-menu-dynamic",
    type: "components:example",
    registryDependencies: ["menu"],
    files: ["example/dropdown-menu-dynamic.tsx"],
  },
  {
    name: "dropdown-menu-section",
    type: "components:example",
    registryDependencies: ["menu"],
    files: ["example/dropdown-menu-section.tsx"],
  },
  {
    name: "dropdown-menu-basic",
    type: "components:example",
    registryDependencies: ["menu"],
    files: ["example/dropdown-menu-basic.tsx"],
  },
  {
    name: "dropdown-menu-checkboxes",
    type: "components:example",
    registryDependencies: ["menu", "checkbox"],
    files: ["example/dropdown-menu-checkboxes.tsx"],
  },
  {
    name: "dropdown-menu-radio-group",
    type: "components:example",
    registryDependencies: ["menu", "radio-group"],
    files: ["example/dropdown-menu-radio-group.tsx"],
  },
  {
    name: "dropzone-demo",
    type: "components:example",
    registryDependencies: ["dropzone"],
    files: ["example/dropzone-demo.tsx"],
  },
  {
    name: "dropzone-file",
    type: "components:example",
    registryDependencies: ["dropzone"],
    files: ["example/dropzone-file.tsx"],
  },
  {
    name: "file-trigger-button-demo",
    type: "components:example",
    files: ["example/file-trigger-button-demo.tsx"],
  },
  {
    name: "input-demo",
    type: "components:example",
    registryDependencies: ["input"],
    files: ["example/input-demo.tsx"],
  },
  {
    name: "input-disabled",
    type: "components:example",
    registryDependencies: ["input"],
    files: ["example/input-disabled.tsx"],
  },
  {
    name: "input-file",
    type: "components:example",
    registryDependencies: ["input"],
    files: ["example/input-file.tsx"],
  },
  {
    name: "input-with-button",
    type: "components:example",
    registryDependencies: ["input", "button"],
    files: ["example/input-with-button.tsx"],
  },
  {
    name: "input-with-label",
    type: "components:example",
    registryDependencies: ["input", "button", "label"],
    files: ["example/input-with-label.tsx"],
  },
  {
    name: "input-with-text",
    type: "components:example",
    registryDependencies: ["input", "button", "label"],
    files: ["example/input-with-text.tsx"],
  },
  {
    name: "label-demo",
    type: "components:example",
    registryDependencies: ["label"],
    files: ["example/label-demo.tsx"],
  },
  {
    name: "link-demo",
    type: "components:example",
    registryDependencies: ["link"],
    files: ["example/link-demo.tsx"],
  },
  {
    name: "link-variants",
    type: "components:example",
    registryDependencies: ["link"],
    files: ["example/link-variants.tsx"],
  },
  {
    name: "meter-demo",
    type: "components:example",
    registryDependencies: ["meter"],
    files: ["example/meter-demo.tsx"],
  },
  {
    name: "meter-value",
    type: "components:example",
    registryDependencies: ["meter"],
    files: ["example/meter-value.tsx"],
  },
  {
    name: "popover-demo",
    type: "components:example",
    registryDependencies: ["popover"],
    files: ["example/popover-demo.tsx"],
  },
  {
    name: "popover-position",
    type: "components:example",
    registryDependencies: ["popover"],
    files: ["example/popover-position.tsx"],
  },
  {
    name: "progress-demo",
    type: "components:example",
    registryDependencies: ["progress"],
    files: ["example/progress-demo.tsx"],
  },
  {
    name: "progress-value",
    type: "components:example",
    registryDependencies: ["progress"],
    files: ["example/progress-value.tsx"],
  },
  {
    name: "radio-group-demo",
    type: "components:example",
    registryDependencies: ["radio-group"],
    files: ["example/radio-group-demo.tsx"],
  },
  {
    name: "radio-group-orientation",
    type: "components:example",
    registryDependencies: ["radio-group"],
    files: ["example/radio-group-orientation.tsx"],
  },
  {
    name: "select-demo",
    type: "components:example",
    registryDependencies: ["select"],
    files: ["example/select-demo.tsx"],
  },
  {
    name: "select-links",
    type: "components:example",
    registryDependencies: ["select"],
    files: ["example/select-links.tsx"],
  },
  {
    name: "select-sections",
    type: "components:example",
    registryDependencies: ["select"],
    files: ["example/select-sections.tsx"],
  },
  {
    name: "separator-demo",
    type: "components:example",
    registryDependencies: ["separator"],
    files: ["example/separator-demo.tsx"],
  },
  {
    name: "select-disabled",
    type: "components:example",
    registryDependencies: ["select"],
    files: ["example/select-disabled.tsx"],
  },
  {
    name: "select-dynamic",
    type: "components:example",
    registryDependencies: ["select"],
    files: ["example/select-dynamic.tsx"],
  },
  {
    name: "slider-demo",
    type: "components:example",
    registryDependencies: ["slider"],
    files: ["example/slider-demo.tsx"],
  },
  {
    name: "slider-value",
    type: "components:example",
    registryDependencies: ["slider"],
    files: ["example/slider-value.tsx"],
  },
  {
    name: "slider-vertical",
    type: "components:example",
    registryDependencies: ["slider"],
    files: ["example/slider-vertical.tsx"],
  },
  {
    name: "switch-demo",
    type: "components:example",
    registryDependencies: ["switch"],
    files: ["example/switch-demo.tsx"],
  },
  {
    name: "switch-disabled",
    type: "components:example",
    registryDependencies: ["switch"],
    files: ["example/switch-disabled.tsx"],
  },
  {
    name: "switch-readonly",
    type: "components:example",
    registryDependencies: ["switch"],
    files: ["example/switch-readonly.tsx"],
  },
  {
    name: "textfield-demo",
    type: "components:example",
    registryDependencies: ["input", "label"],
    files: ["example/textfield-demo.tsx"],
  },
  {
    name: "textarea-demo",
    type: "components:example",
    registryDependencies: ["textarea"],
    files: ["example/textarea-demo.tsx"],
  },
  {
    name: "textfield-textarea",
    type: "components:example",
    registryDependencies: ["input", "label"],
    files: ["example/textfield-textarea.tsx"],
  },
  {
    name: "textfield-desc",
    type: "components:example",
    registryDependencies: ["input", "label"],
    files: ["example/textfield-desc.tsx"],
  },
  {
    name: "textarea-disabled",
    type: "components:example",
    registryDependencies: ["textarea"],
    files: ["example/textarea-disabled.tsx"],
  },
  {
    name: "textarea-with-button",
    type: "components:example",
    registryDependencies: ["textarea", "button"],
    files: ["example/textarea-with-button.tsx"],
  },
  {
    name: "textarea-with-label",
    type: "components:example",
    registryDependencies: ["textarea", "label"],
    files: ["example/textarea-with-label.tsx"],
  },
  {
    name: "textarea-with-text",
    type: "components:example",
    registryDependencies: ["textarea", "label"],
    files: ["example/textarea-with-text.tsx"],
  },
  {
    name: "toggle-demo",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-demo.tsx"],
  },
  {
    name: "toggle-disabled",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-disabled.tsx"],
  },
  {
    name: "toggle-lg",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-lg.tsx"],
  },
  {
    name: "toggle-outline",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-outline.tsx"],
  },
  {
    name: "toggle-sm",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-sm.tsx"],
  },
  {
    name: "toggle-with-text",
    type: "components:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-with-text.tsx"],
  },
  {
    name: "tooltip-demo",
    type: "components:example",
    registryDependencies: ["tooltip"],
    files: ["example/tooltip-demo.tsx"],
  },
  {
    name: "tooltip-position",
    type: "components:example",
    registryDependencies: ["tooltip"],
    files: ["example/tooltip-position.tsx"],
  },
  {
    name: "mode-toggle",
    type: "components:example",
    files: ["example/mode-toggle.tsx"],
  },
]

export const registry: Registry = [...ui, ...example]
