import { Registry } from "@/registry/schema"

const ui: Registry = [
  {
    name: "breadcrumbs",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button"],
    files: ["ui/breadcrumbs.tsx"],
  },


  {
    name: "checkbox",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["label"],
    files: ["ui/checkbox.tsx"],
  },
  {
    name: "color",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/color.tsx"],
  },
  {
    name: "combobox",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/combobox.tsx"],
  },
  {
    name: "date-picker",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "popover"],
    files: ["ui/date-picker.tsx"],
  },
  {
    name: "dialog",
    type: "components:ui",
    dependencies: ["react-aria-components", "class-variance-authority"],
    files: ["ui/dialog.tsx"],
  },
  {
    name: "dropzone",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/dropzone.tsx"],
  },
  {
    name: "input",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/input.tsx"],
  },
  {
    name: "label",
    type: "components:ui",
    dependencies: ["react-aria-components", "class-variance-authority"],
    files: ["ui/label.tsx"],
  },
  {
    name: "link",
    type: "components:ui",
    dependencies: ["react-aria-components", "class-variance-authority"],
    registryDependencies: ["button"],
    files: ["ui/link.tsx"],
  },
  {
    name: "menu",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/menu.tsx"],
  },
  {
    name: "meter",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/meter.tsx"],
  },
  {
    name: "popover",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/popover.tsx"],
  },
  {
    name: "progress",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/progress.tsx"],
  },
  {
    name: "radio-group",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["label"],
    files: ["ui/radio-group.tsx"],
  },
  {
    name: "searchfield",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/searchfield.tsx"],
  },
  {
    name: "select",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/select.tsx"],
  },
  {
    name: "separator",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/separator.tsx"],
  },
  {
    name: "slider",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/slider.tsx"],
  },
  {
    name: "switch",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/switch.tsx"],
  },
  {
    name: "tabs",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/tabs.tsx"],
  },
  {
    name: "textarea",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/textarea.tsx"],
  },

  {
    name: "tooltip",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/tooltip.tsx"],
  },
  // NEW CHECKED
  {
    name: "button",
    type: "components:ui",
    dependencies: ["react-aria-components", "class-variance-authority"],
    files: ["ui/button.tsx"],
  },
  {
    name: "toggle",
    type: "components:ui",
    dependencies: ["react-aria-components", "class-variance-authority"],
    files: ["ui/toggle.tsx"],
  },
  {
    name: "grid-list",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["checkbox"],
    files: ["ui/grid-list.tsx"],
  },
  {
    name: "list-box",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/grid-list.tsx"],
  },
  {
    name: "tag-group",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    files: ["ui/tag-group.tsx"],
  },

  {
    name: "calendar",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button"],
    files: ["ui/calendar.tsx"],
  },

  {
    name: "datefield",
    type: "components:ui",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button"],
    files: ["ui/datefield.tsx"],
  },

]

const example: Registry = [
  {
    name: "breadcrumbs-demo",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-demo.tsx"],
  },
  {
    name: "breadcrumbs-dropdown",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-dropdown.tsx"],
  },
  {
    name: "breadcrumbs-disabled",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-disabled.tsx"],
  },
  {
    name: "breadcrumbs-ellipsis",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-ellipsis.tsx"],
  },
  {
    name: "breadcrumbs-separator",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-separator.tsx"],
  },
  {
    name: "breadcrumbs-items",
    type: "components:example/breadcrumbs",
    registryDependencies: ["breadcrumbs"],
    files: ["example/breadcrumbs/breadcrumbs-items.tsx"],
  },


  {
    name: "color-area",
    type: "components:example/color",
    registryDependencies: ["color"],
    files: ["example/color/color-area.tsx"],
  },
  {
    name: "color-picker-eye",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-eye.tsx"],
  },
  {
    name: "color-picker-hex",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hex.tsx"],
  },
  {
    name: "color-picker-slider",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-slider.tsx"],
  },
  {
    name: "color-picker-hexa",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hexa.tsx"],
  }, {
    name: "color-picker-hsb",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hsb.tsx"],
  }, {
    name: "color-picker-hsba",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hsba.tsx"],
  },
  {
    name: "color-picker-multi",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-multi.tsx"],
  },
  {
    name: "color-picker-hsl",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hsl.tsx"],
  }, {
    name: "color-picker-hsla",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-hsla.tsx"],
  }, {
    name: "color-picker-rgb",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-rgb.tsx"],
  }, {
    name: "color-picker-rgba",
    type: "components:example/color/pickers",
    registryDependencies: ["color"],
    files: ["example/color/pickers/color-picker-rgba.tsx"],
  },
  {
    name: "color-slider",
    type: "components:example/color",
    registryDependencies: ["color"],
    files: ["example/color/color-slider.tsx"],
  },
  {
    name: "color-swatch-picker",
    type: "components:example/color",
    registryDependencies: ["color"],
    files: ["example/color/color-swatch-picker.tsx"],
  },
  {
    name: "color-wheel",
    type: "components:example/color",
    registryDependencies: ["color"],
    files: ["example/color/color-wheel.tsx"],
  },
  {
    name: "combobox-basic",
    type: "components:example/combobox",
    registryDependencies: ["combobox"],
    files: ["example/combobox/combobox-basic.tsx"],
  },
  {
    name: "combobox-demo",
    type: "components:example/combobox",
    registryDependencies: ["combobox"],
    files: ["example/combobox/combobox-demo.tsx"],
  },
  {
    name: "combobox-dynamic",
    type: "components:example/combobox",
    registryDependencies: ["combobox"],
    files: ["example/combobox/combobox-dynamic.tsx"],
  },
  {
    name: "combobox-link",
    type: "components:example/combobox",
    registryDependencies: ["combobox"],
    files: ["example/combobox/combobox-link.tsx"],
  },
  {
    name: "combobox-section",
    type: "components:example/combobox",
    registryDependencies: ["combobox"],
    files: ["example/combobox/combobox-section.tsx"],
  },
  {
    name: "dialog-alert-demo",
    type: "components:example/dialog",
    registryDependencies: ["dialog"],
    files: ["example/dialog/dialog-alert-demo.tsx"],
  },
  {
    name: "dialog-close-button",
    type: "components:example/dialog",
    registryDependencies: ["dialog"],
    files: ["example/dialog/dialog-close-button.tsx"],
  },
  {
    name: "dialog-demo",
    type: "components:example/dialog",
    registryDependencies: ["dialog"],
    files: ["example/dialog/dialog-demo.tsx"],
  },
  {
    name: "dialog-sheet",
    type: "components:example/dialog",
    registryDependencies: ["dialog"],
    files: ["example/dialog/dialog-sheet.tsx"],
  },
  {
    name: "file-trigger-button-demo",
    type: "components:example/file-trigger",
    registryDependencies: ["button"],
    files: ["example/file-trigger/file-trigger-button-demo.tsx"],
  },
  {
    name: "input-demo",
    type: "components:example/input",
    registryDependencies: ["input"],
    files: ["example/input/input-demo.tsx"],
  },
  {
    name: "input-disabled",
    type: "components:example/input",
    registryDependencies: ["input"],
    files: ["example/input/input-disabled.tsx"],
  },
  {
    name: "input-file",
    type: "components:example/input",
    registryDependencies: ["input"],
    files: ["example/input/input-file.tsx"],
  },
  {
    name: "label-demo",
    type: "components:example/label",
    registryDependencies: ["label"],
    files: ["example/label/label-demo.tsx"],
  },
  {
    name: "link-demo",
    type: "components:example/link",
    registryDependencies: ["link"],
    files: ["example/link/link-demo.tsx"],
  },
  {
    name: "link-variants",
    type: "components:example/link",
    registryDependencies: ["link"],
    files: ["example/link/link-variants.tsx"],
  },

  {
    name: "meter-demo",
    type: "components:example/meter",
    registryDependencies: ["meter"],
    files: ["example/meter/meter-demo.tsx"],
  },
  {
    name: "meter-value",
    type: "components:example/meter",
    registryDependencies: ["meter"],
    files: ["example/meter/meter-value.tsx"],
  },
  {
    name: "popover-demo",
    type: "components:example/popover",
    registryDependencies: ["popover"],
    files: ["example/popover/popover-demo.tsx"],
  },
  {
    name: "popover-position",
    type: "components:example/popover",
    registryDependencies: ["popover"],
    files: ["example/popover/popover-position.tsx"],
  },
  {
    name: "progress-demo",
    type: "components:example/progress",
    registryDependencies: ["progress"],
    files: ["example/progress/progress-demo.tsx"],
  },
  {
    name: "progress-value",
    type: "components:example/progress",
    registryDependencies: ["progress"],
    files: ["example/progress/progress-value.tsx"],
  },
  {
    name: "radio-group-demo",
    type: "components:example/radio",
    registryDependencies: ["radio-group"],
    files: ["example/radio/radio-group-demo.tsx"],
  },
  {
    name: "radio-group-orientation",
    type: "components:example/radio",
    registryDependencies: ["radio-group"],
    files: ["example/radio/radio-group-orientation.tsx"],
  },
  {
    name: "searchfield-demo",
    type: "components:example/searchfield",
    registryDependencies: ["searchfield"],
    files: ["example/searchfield/searchfield-demo.tsx"],
  },
  {
    name: "searchfield-disabled",
    type: "components:example/searchfield",
    registryDependencies: ["searchfield"],
    files: ["example/searchfield/searchfield-disabled.tsx"],
  },
  {
    name: "select-demo",
    type: "components:example/select",
    registryDependencies: ["select"],
    files: ["example/select/select-demo.tsx"],
  },
  {
    name: "select-disabled",
    type: "components:example/select",
    registryDependencies: ["select"],
    files: ["example/select/select-disabled.tsx"],
  },
  {
    name: "select-dynamic",
    type: "components:example/select",
    registryDependencies: ["select"],
    files: ["example/select/select-dynamic.tsx"],
  },
  {
    name: "select-links",
    type: "components:example/select",
    registryDependencies: ["select"],
    files: ["example/select/select-links.tsx"],
  },
  {
    name: "select-sections",
    type: "components:example/select",
    registryDependencies: ["select"],
    files: ["example/select/select-sections.tsx"],
  },
  {
    name: "separator-demo",
    type: "components:example/separator",
    registryDependencies: ["separator"],
    files: ["example/separator/separator-demo.tsx"],
  },
  {
    name: "slider-demo",
    type: "components:example/slider",
    registryDependencies: ["slider"],
    files: ["example/slider/slider-demo.tsx"],
  },
  {
    name: "slider-value",
    type: "components:example/slider",
    registryDependencies: ["slider"],
    files: ["example/slider/slider-value.tsx"],
  },
  {
    name: "slider-vertical",
    type: "components:example/slider",
    registryDependencies: ["slider"],
    files: ["example/slider/slider-vertical.tsx"],
  },
  {
    name: "switch-demo",
    type: "components:example/switch",
    registryDependencies: ["switch"],
    files: ["example/switch/switch-demo.tsx"],
  },
  {
    name: "switch-disabled",
    type: "components:example/switch",
    registryDependencies: ["switch"],
    files: ["example/switch/switch-disabled.tsx"],
  },
  {
    name: "switch-readonly",
    type: "components:example/switch",
    registryDependencies: ["switch"],
    files: ["example/switch/switch-readonly.tsx"],
  },
  {
    name: "tabs-demo",
    type: "components:example/tabs",
    registryDependencies: ["tabs"],
    files: ["example/tabs/tabs-demo.tsx"],
  },
  {
    name: "textarea-demo",
    type: "components:example/textarea",
    registryDependencies: ["textarea"],
    files: ["example/textarea/textarea-demo.tsx"],
  },
  {
    name: "textarea-disabled",
    type: "components:example/textarea",
    registryDependencies: ["textarea"],
    files: ["example/textarea/textarea-disabled.tsx"],
  },
  {
    name: "textarea-with-button",
    type: "components:example/textarea",
    registryDependencies: ["textarea"],
    files: ["example/textarea/textarea-with-button.tsx"],
  },
  {
    name: "textarea-with-label",
    type: "components:example/textarea",
    registryDependencies: ["textarea"],
    files: ["example/textarea/textarea-with-label.tsx"],
  },
  {
    name: "textarea-with-text",
    type: "components:example/textarea",
    registryDependencies: ["textarea"],
    files: ["example/textarea/textarea-with-text.tsx"],
  },
  {
    name: "textfield-demo",
    type: "components:example/textfield",
    registryDependencies: ["textfield"],
    files: ["example/textfield/textfield-demo.tsx"],
  },
  {
    name: "textfield-desc",
    type: "components:example/textfield",
    registryDependencies: ["textfield"],
    files: ["example/textfield/textfield-desc.tsx"],
  },
  {
    name: "textfield-textarea",
    type: "components:example/textfield",
    registryDependencies: ["textfield"],
    files: ["example/textfield/textfield-textarea.tsx"],
  },

  {
    name: "tooltip-demo",
    type: "components:example/tooltip",
    registryDependencies: ["tooltip"],
    files: ["example/tooltip/tooltip-demo.tsx"],
  },
  {
    name: "tooltip-position",
    type: "components:example/tooltip",
    registryDependencies: ["tooltip"],
    files: ["example/tooltip/tooltip-position.tsx"],
  },
  {
    name: "button-demo",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-demo.tsx"],
  },
  {
    name: "button-ghost",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-ghost.tsx"],
  },
  {
    name: "button-icon",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-icon.tsx"],
  },
  {
    name: "button-link",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-link.tsx"],
  },
  {
    name: "button-loading",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-loading.tsx"],
  },
  {
    name: "button-press",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-press.tsx"],
  },
  {
    name: "button-secondary",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-secondary.tsx"],
  },
  {
    name: "button-with-icon",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-with-icon.tsx"],
  },
  {
    name: "button-outline",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-outline.tsx"],
  },
  {
    name: "button-destructive",
    type: "components:example/button",
    registryDependencies: ["button"],
    files: ["example/button/button-destructive.tsx"],
  },
  {
    name: "toggle-demo",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-demo.tsx"],
  },
  {
    name: "toggle-disabled",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-disabled.tsx"],
  },
  {
    name: "toggle-lg",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-lg.tsx"],
  },
  {
    name: "toggle-outline",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-outline.tsx"],
  },
  {
    name: "toggle-sm",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-sm.tsx"],
  },
  {
    name: "toggle-with-text",
    type: "components:example/toggle",
    registryDependencies: ["toggle"],
    files: ["example/toggle/toggle-with-text.tsx"],
  },


  // GridList
  {
    name: "grid-list-content",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-content.tsx"],
  },
  {
    name: "grid-list-demo",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-demo.tsx"],
  },
  {
    name: "grid-list-direct-row-actions",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-direct-row-actions.tsx"],
  },
  {
    name: "grid-list-disabled-behavior",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-disabled-behavior.tsx"],
  },
  {
    name: "grid-list-disabled-items",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-disabled-items.tsx"],
  },
  {
    name: "grid-list-disabled-keys",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-disabled-keys.tsx"],
  },
  {
    name: "grid-list-disallow-empty",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-disallow-empty.tsx"],
  },
  {
    name: "grid-list-drag-between",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-drag-between.tsx"],
  },
  {
    name: "grid-list-drag-drop",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-drag-drop.tsx"],
  },
  {
    name: "grid-list-empty",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-empty.tsx"],
  },
  {
    name: "grid-list-links",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-links.tsx"],
  },
  {
    name: "grid-list-multi-select",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-multi-select.tsx"],
  },
  {
    name: "grid-list-replace",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-replace.tsx"],
  },
  {
    name: "grid-list-row-actions",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-row-actions.tsx"],
  },
  {
    name: "grid-list-single-select",
    type: "components:example/grid-list",
    registryDependencies: ["grid-list"],
    files: ["example/grid-list/grid-list-single-select.tsx"],
  },

  // ListBox
  {
    name: "list-box-content",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-content.tsx"],
  },
  {
    name: "list-box-demo",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-demo.tsx"],
  },
  {
    name: "list-box-disabled-items",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-disabled-items.tsx"],
  },
  {
    name: "list-box-disabled-keys",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-disabled-keys.tsx"],
  },
  {
    name: "list-box-drag-between",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-drag-between.tsx"],
  },
  {
    name: "list-box-drag-drop",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-drag-drop.tsx"],
  },
  {
    name: "list-box-dynamic",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-dynamic.tsx"],
  },
  {
    name: "list-box-empty",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-empty.tsx"],
  },
  {
    name: "list-box-links-replace",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-links-replace.tsx"],
  },
  {
    name: "list-box-links",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-links.tsx"],
  },
  {
    name: "list-box-sections",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-sections.tsx"],
  },
  {
    name: "list-box-selection-replace",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-selection-replace.tsx"],
  },
  {
    name: "list-box-text-slot",
    type: "components:example/list-box",
    registryDependencies: ["list-box"],
    files: ["example/list-box/list-box-text-slot.tsx"],
  },


  // Menu
  {
    name: "menu-content",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-content.tsx"],
  },
  {
    name: "menu-demo",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-demo.tsx"],
  },
  {
    name: "menu-disabled-items",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-disabled-items.tsx"],
  },
  {
    name: "menu-disabled-keys",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-disabled-keys.tsx"],
  },
  {
    name: "menu-links",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-links.tsx"],
  },
  {
    name: "menu-long-press",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-long-press.tsx"],
  },
  {
    name: "menu-sections-dynamic",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-sections-dynamic.tsx"],
  },
  {
    name: "menu-sections",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-sections.tsx"],
  },
  {
    name: "menu-selection-multiple",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-selection-multiple.tsx"],
  },
  {
    name: "menu-selection-single",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-selection-single.tsx"],
  },
  {
    name: "menu-separators",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-separators.tsx"],
  },
  {
    name: "menu-sub-menu-dynamic",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-sub-menu-dynamic.tsx"],
  },
  {
    name: "menu-sub-menu",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-sub-menu.tsx"],
  },
  {
    name: "menu-text-slots",
    type: "components:example/menu",
    registryDependencies: ["menu"],
    files: ["example/menu/menu-text-slots.tsx"],
  },

  //TagGroup
  {
    name: "tag-error-text",
    type: "components:example/tag-group",
    registryDependencies: ["tag"],
    files: ["example/tag/tag-error-text.tsx"],
  },
  {
    name: "tag-group-demo",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-demo.tsx"],
  },
  {
    name: "tag-group-disabled-items",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-disabled-items.tsx"],
  },
  {
    name: "tag-group-disabled-keys",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-disabled-keys.tsx"],
  },
  {
    name: "tag-group-empty",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-empty.tsx"],
  },
  {
    name: "tag-group-helper",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-helper.tsx"],
  },
  {
    name: "tag-group-links",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-links.tsx"],
  },
  {
    name: "tag-group-remove",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-remove.tsx"],
  },
  {
    name: "tag-group-selection",
    type: "components:example/tag-group",
    registryDependencies: ["tag-group"],
    files: ["example/tag-group/tag-group-selection.tsx"],
  },

  // Calendar
  {
    name: "calendar-demo",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-demo.tsx"],
  },
  {
    name: "calendar-disabled",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-disabled.tsx"],
  },
  {
    name: "calendar-error",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-error.tsx"],
  },
  {
    name: "calendar-multi",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-multi.tsx"],
  },
  {
    name: "calendar-readonly",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-readonly.tsx"],
  },
  {
    name: "calendar-unavailable",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-unavailable.tsx"],
  },
  {
    name: "calendar-validation",
    type: "components:example/calendar",
    registryDependencies: ["calendar"],
    files: ["example/calendar/calendar-validation.tsx"],
  },

  // DateField
  {
    name: "datefield-demo",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-demo.tsx"],
  },
  {
    name: "datefield-description",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-description.tsx"],
  },
  {
    name: "datefield-granularity",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-granularity.tsx"],
  },
  {
    name: "datefield-timezone",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-timezone.tsx"],
  },
  {
    name: "datefield-validation-min-max",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-validation-min-max.tsx"],
  },
  {
    name: "datefield-validation",
    type: "components:example/datefield",
    registryDependencies: ["datefield"],
    files: ["example/datefield/datefield-validation.tsx"],
  },

  // Datepicker
  {
    name: "datepicker-custom-validation",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-custom-validation.tsx"],
  },
  {
    name: "datepicker-demo",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-demo.tsx"],
  },
  {
    name: "datepicker-description",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-description.tsx"],
  },
  {
    name: "datepicker-granularity",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-granularity.tsx"],
  },
  {
    name: "datepicker-min-max",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-min-max.tsx"],
  },
  {
    name: "datepicker-timezone",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-timezone.tsx"],
  },
  {
    name: "datepicker-unavailable",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-unavailable.tsx"],
  },
  {
    name: "datepicker-validation",
    type: "components:example/datepicker",
    registryDependencies: ["datepicker"],
    files: ["example/datepicker/datepicker-validation.tsx"],
  },

  //Date range picker
  {
    name: "date-range-non-continuous",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-non-continuous.tsx"],
  },
  {
    name: "date-range-picker-custom-validation",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-custom-validation.tsx"],
  },
  {
    name: "date-range-picker-demo",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-demo.tsx"],
  },
  {
    name: "date-range-picker-description",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-description.tsx"],
  },
  {
    name: "date-range-picker-granularity",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-granularity.tsx"],
  },
  {
    name: "date-range-picker-min-max",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-min-max.tsx"],
  },
  {
    name: "date-range-picker-timezone",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-timezone.tsx"],
  },
  {
    name: "date-range-picker-validation",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-picker-validation.tsx"],
  },
  {
    name: "date-range-unavailable",
    type: "components:example/date-range-picker",
    registryDependencies: ["date-range-picker"],
    files: ["example/date-range-picker/date-range-unavailable.tsx"],
  },

  // Range Calendar

  {
    name: "range-calendar-demo",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-demo.tsx"],
  },
  {
    name: "range-calendar-disabled",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-disabled.tsx"],
  },
  {
    name: "range-calendar-error",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-error.tsx"],
  },
  {
    name: "range-calendar-multi-month",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-multi-month.tsx"],
  },
  {
    name: "range-calendar-non-continuous",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-non-continuous.tsx"],
  },
  {
    name: "range-calendar-readonly",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-readonly.tsx"],
  },
  {
    name: "range-calendar-unavailable",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-unavailable.tsx"],
  },
  {
    name: "range-calendar-validation",
    type: "components:example/range-calendar",
    registryDependencies: ["range-calendar"],
    files: ["example/range-calendar/range-calendar-validation.tsx"],
  }

  // TimeField
  ,
  {
    name: "timefield-custom-validation",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-custom-validation.tsx"],
  },
  {
    name: "timefield-demo",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-demo.tsx"],
  },
  {
    name: "timefield-description",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-description.tsx"],
  },
  {
    name: "timefield-granularity",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-granularity.tsx"],
  },
  {
    name: "timefield-min-max",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-min-max.tsx"],
  },
  {
    name: "timefield-timezone",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-timezone.tsx"],
  },
  {
    name: "timefield-validation",
    type: "components:example/timefield",
    registryDependencies: ["timefield"],
    files: ["example/timefield/timefield-validation.tsx"],
  },

  // Dropzone
  {
    name: "dropzone-demo",
    type: "components:example/dropzone",
    registryDependencies: ["dropzone"],
    files: ["example/dropzone/dropzone-demo.tsx"],
  },
  {
    name: "dropzone-file",
    type: "components:example/dropzone",
    registryDependencies: ["dropzone"],
    files: ["example/dropzone/dropzone-file.tsx"],
  },

  // Checkbox

  {
    name: "checkbox-demo",
    type: "components:example/checkbox",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox/checkbox-demo.tsx"],
  },
  {
    name: "checkbox-disabled",
    type: "components:example/checkbox",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox/checkbox-disabled.tsx"],
  },
  {
    name: "checkbox-indeterminate",
    type: "components:example/checkbox",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox/checkbox-indeterminate.tsx"],
  },
  {
    name: "checkbox-readonly",
    type: "components:example/checkbox",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox/checkbox-readonly.tsx"],
  },
  {
    name: "checkbox-validation",
    type: "components:example/checkbox",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox/checkbox-validation.tsx"],
  },

  // CheckboxGroup

  {
    name: "checkbox-group-demo",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-demo.tsx"],
  },
  {
    name: "checkbox-group-description",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-description.tsx"],
  },
  {
    name: "checkbox-group-disabled-individual",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-disabled-individual.tsx"],
  },
  {
    name: "checkbox-group-disabled",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-disabled.tsx"],
  },
  {
    name: "checkbox-group-individual-validation",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-individual-validation.tsx"],
  },
  {
    name: "checkbox-group-readonly",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-readonly.tsx"],
  },
  {
    name: "checkbox-group-validation",
    type: "components:example/checkbox-group",
    registryDependencies: ["checkbox-group"],
    files: ["example/checkbox-group/checkbox-group-validation.tsx"],
  }

]

export const registry: Registry = [...ui, ...example]
